### PR TITLE
Re-Organised Documentation and Readme

### PR DESCRIPTION
**Pull request by Chelsea-Fox**
I have separated the large readme.md to `docs/Installation.md` & `Configuration.md`

This way the readme file is smaller and much more elegant whilst keeping the important documentation still easily accessible.

This also allows for future changes to the documentation in case there are large scale changes in the future.

### CODE REVIEW

**Comment by AlphaNecron** [comment]
Can you add these files to the exception of CI?

**Comment by Chelsea-Fox** [comment]
> Can you add these files to the exception of CI?

Should be all good now

**Comment by AlphaNecron** [comment]
Btw next time **clone** the repository and commit changes there, you shouldn't commit one change for each file like that, looks annoying though. Thanks for your contribution.

**Review by AlphaNecron — APPROVED** [review]

**Comment by Chelsea-Fox** [comment]
> Btw next time **clone** the repository and commit changes there, you shouldn't commit one change for each file like that, looks annoying though. Thanks for your contribution.

No Worries at all, makes sense.

As I use the void I might help out with docs or other little bits here and there.

Thanks for the cool software.

**Comment by AlphaNecron** [comment]
Thanks! Stay tuned for Void `v1` :wink:

**Pull request merged**
